-- AlterTable
ALTER TABLE "users" ALTER COLUMN "credits" SET DEFAULT 5,
ALTER COLUMN "credits" SET DATA TYPE DOUBLE PRECISION USING "credits"::DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "generation_jobs" ALTER COLUMN "credits_used" SET DATA TYPE DOUBLE PRECISION USING "credits_used"::DOUBLE PRECISION;
